export{}
/**
 * @details 
 * 
 * THIS IS THE FILE WHERE THE USER SETTINGS RELATED TO THE APP WILL BE FETCHED FROM THE 
 * BACKEND AND WILL EXPORT AS A CONTEXT TO ALL THE PAGES HEREFORTH 
 * 
 * RIGHT NOW I THINK WE CAN INCLUDE SOME SETTINGS LIKE 
 *  - ENABLE ANIMATIONS 
 *  
 */

